# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
[plugins]
"rocks-treesitter.nvim" = "1.2.0"
"alpha-nvim" = "scm"
"auto-session" = "2.5.0"
"comment.nvim" = "0.8.0"
"lualine.nvim" = "scm"
"mason.nvim" = "scm"
"mason-lspconfig.nvim" = "1.31.0"
"nvim-autopairs" = "scm"
"nvim-lspconfig" = "1.0.0"
"nvim-tree.lua" = "1.6.0"
"obsidian.nvim" = "3.9.0"
"plenary.nvim" = "scm"
"popup.nvim" = "scm"
"project.nvim" = "scm"
"rocks-config.nvim" = "3.0.0"
"rocks-git.nvim" = "2.5.1"
"rocks.nvim" = "2.41.1"
"telescope.nvim" = "scm"
"toggleterm.nvim" = "2.12.0"
"nvim-dap" = "0.8.0"
"nvim-dap-go" = "scm"
"mini.ai" = "0.9.0"
"go.nvim" = "0.9.0"
"mini.clue" = "0.14.0"
"nvim-treesitter" = "scm"
"tree-sitter-toml" = "0.0.30"
"tree-sitter-go" = "0.0.35"
"tree-sitter-gomod" = "0.0.30"
tree-sitter-yaml = "0.0.29"
tree-sitter-fish = "0.0.29"
tree-sitter-nix = "0.0.50"
tree-sitter-gosum = "0.0.29"
tree-sitter-ruby = "0.0.33"
tree-sitter-yuck = "0.0.29"
tree-sitter-kdl = "0.0.29"
tree-sitter-idl = "0.0.31"
tree-sitter-capnp = "0.0.29"
tree-sitter-beancount = "0.0.30"
tree-sitter-gitignore = "0.0.29"
tree-sitter-c_sharp = "0.0.36"
tree-sitter-ini = "0.0.29"
"mini.snippets" = "0.15.0"
 
[treesitter]
auto_highlight = "all"
# NOTE: These are parsers, not filetypes.
auto_install = "prompt" # true | false
config_path = "rocks-treesitter.toml"

# NOTE: These are filetypes
disable = [
  "lhaskell"
]

[plugins.harpoon]
git = "github:theprimeagen/harpoon"
branch = "harpoon2"

[plugins.vim-sneak]
git = "github:justinmk/vim-sneak"
rev = "1.10.0"

[plugins.vim-endwise]
git = "github:metiulekm/nvim-treesitter-endwise"
branch = "master"

[plugins.blink]
git = "github:saghen/blink.cmp"
rev = "v0.11.0"

[plugins.vim-table-mode]
git = "github:dhruvasagar/vim-table-mode"
branch = "master"

[plugins.gitsigns]
git = "github:lewis6991/gitsigns.nvim"
rev = "v0.9.0"

[plugins.gruvbox-material]
git = "github:sainnhe/gruvbox-material"
branch = "master"

[plugins.vim-rspec]
git = "github:thoughtbot/vim-rspec"
branch = "main"

[config]
plugins_dir = "plugins/"
auto_setup = false
