# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"alpha-nvim" = "scm"
"auto-session" = "2.5.0"
"cmp-buffer" = "scm"
"cmp-cmdline" = "scm"
"cmp-nvim-lsp" = "scm"
"cmp-path" = "scm"
"cmp_luasnip" = "scm"
"comment.nvim" = "0.8.0"
"gruvbox.nvim" = "2.0.0"
"lualine.nvim" = "scm"
"luasnip" = "2.3.0"
"mason.nvim" = "scm"
"mason-lspconfig.nvim" = "1.31.0"
"nvim-autopairs" = "scm"
"nvim-lspconfig" = "1.0.0"
"nvim-tree.lua" = "1.6.0"
"obsidian.nvim" = "3.9.0"
"plenary.nvim" = "scm"
"popup.nvim" = "scm"
"project.nvim" = "scm"
"rocks-config.nvim" = "3.0.0"
"rocks-git.nvim" = "2.5.1"
"rocks-treesitter.nvim" = "scm"
"rocks.nvim" = "2.41.1"
"telescope.nvim" = "scm"
"toggleterm.nvim" = "2.12.0"
"which-key.nvim" = "3.13.3"
"nvim-dap" = "0.8.0"
"nvim-dap-go" = "scm"
"mini.ai" = "0.9.0"

[treesitter]
auto_highlight = "all"
# NOTE: These are parsers, not filetypes.
auto_install = "prompt" # true | false

# NOTE: These are filetypes
disable = [
  "lhaskell"
]

[plugins.harpoon]
git = "github:theprimeagen/harpoon"
branch = "harpoon2"

[plugins.vim-sneak]
git = "github:justinmk/vim-sneak"
rev = "1.10.0"

[plugins.nvim-cmp]
git = "github:hrsh7th/nvim-cmp"
branch = "main"

[plugins.vim-table-mode]
git = "github:dhruvasagar/vim-table-mode"
branch = "master"

[plugins.gitsigns]
git = "github:lewis6991/gitsigns.nvim"
rev = "v0.9.0"

[plugins.gruvbox-material]
git = "github:sainnhe/gruvbox-material"
branch = "master"

[plugins.vim-rspec]
git = "github:thoughtbot/vim-rspec"
branch = "main"

[config]
plugins_dir = "plugins/"
auto_setup = false
